name: Déploiement en production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BETA_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_BETA_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_API_PILOTAGE_PROJECT }}
        SENTRY_URL: ${{ secrets.SENTRY_BETA_URL }}
      with:
        environment: production
        ignore_missing: true
        ignore_empty: true
