name: Déploiement manuel app staging clever

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow

    - uses: 47ng/actions-clever-cloud@v1.2.0
      with:
        appID: ${{ secrets.CLEVER_APP_ADMIN_API_STAGING_ID }}
        timeout: 300 #5 minutes before move on (in case of never exit even though a deployment is successful)
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

    - uses: actions/checkout@v4
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BETA_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_BETA_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_API_PILOTAGE_PROJECT }}
        SENTRY_URL: ${{ secrets.SENTRY_BETA_URL }}
      with:
        environment: staging
        ignore_missing: true
        ignore_empty: true
